---
k3s_is_server: "{{ 'k3s_server' in group_names }}"
k3s_service_name: "{{ 'k3s' if k3s_is_server else 'k3s-agent' }}"
k3s_config_dir: /etc/rancher/k3s
k3s_install_script: /usr/local/share/k3s/install.sh
k3s_token_file: /var/lib/rancher/k3s/server/node-token

k3s_server_config_base:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ ansible_host }}"
  write-kubeconfig-mode: "0600"

k3s_server_host: "{{ groups['k3s_server'][0] }}"
k3s_server_url: "https://{{ hostvars[k3s_server_host]['ansible_host'] }}:{{ k3s_api_port }}"

k3s_agent_config_base:
  server: "{{ k3s_server_url }}"
  node-ip: "{{ ansible_host }}"
