#!/usr/bin/env python3
"""Render an Ansible YAML inventory from `terraform output -json`.

Reads terraform outputs on stdin and writes the inventory to the path given
as the first argument (or to stdout). The file is only written on success.

    terraform -chdir=terraform/environments/lab output -json \
        | scripts/generate-inventory.py ansible/inventory/hosts.yml
"""

import json
import sys

GROUPS = {"server": "k3s_server", "agent": "k3s_agent"}


def fail(message: str) -> int:
    print(f"error: {message}", file=sys.stderr)
    return 1


def render(nodes: dict, ssh_user: str) -> str:
    groups = {group: [] for group in GROUPS.values()}
    for name, node in sorted(nodes.items()):
        groups[GROUPS[node["role"]]].append((name, node["ipv4_address"]))

    lines = [
        "---",
        "# Generated by scripts/generate-inventory.py, do not edit.",
        "all:",
        "  vars:",
        f"    ansible_user: {ssh_user}",
        "  children:",
        "    k3s_cluster:",
        "      children:",
    ]
    for group, hosts in groups.items():
        lines.append(f"        {group}:")
        if not hosts:
            lines.append("          hosts: {}")
            continue
        lines.append("          hosts:")
        for name, ip in hosts:
            lines.append(f"            {name}:")
            lines.append(f"              ansible_host: {ip}")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        outputs = json.load(sys.stdin)
        nodes = outputs["nodes"]["value"]
        ssh_user = outputs["ssh_user"]["value"]
    except json.JSONDecodeError as exc:
        return fail(f"terraform output is not valid JSON: {exc}")
    except KeyError as exc:
        return fail(f"missing terraform output {exc}")

    if not nodes:
        return fail("terraform output 'nodes' is empty")
    for name, node in nodes.items():
        if node.get("role") not in GROUPS:
            return fail(f"node {name} has unknown role {node.get('role')!r}")

    inventory = render(nodes, ssh_user)
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w", encoding="utf-8") as fh:
            fh.write(inventory)
    else:
        sys.stdout.write(inventory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
